# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
    - task: run
      # silent: true

  build:
    cmds:
    - go build -o bin/ ./...

  docker-build:
    cmds:
    - docker build -t taskmedia/pci:local .

  docker-run:
    cmds:
    - |
      docker run \
        --name pci \
        -p 8080:8080 \
        --env PCI_PSQLHOST=host.docker.internal \
        --rm \
        taskmedia/pci:local

  # lint:
  #   cmds:
  #   - golangci-lint run ./...

  run:
    cmds:
    - go run ./...

  # test:
  #   cmds:
  #   - go test -v ./...
