apiVersion: v2
name: processionCheckIn
description: |
  Helm chart to deploy processionCheckIn application

type: application

version: 0.1.0

appVersion: 0.1.0

dependencies:
- name: postgresql
  version: 12.2.2
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
